{
 "title": "Broker",
 "description": "Solace Broker Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"host\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Redundancy Activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"redundancy\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"primary-status-activity\" or r[\"_field\"] == \"backup-status-activity\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> map(fn: (r) => ({ activity_status: \n    if r[\"active-standby-role\"] == \"Primary\" then r[\"primary-status-activity\"] \n    else if r[\"active-standby-role\"] == \"Backup\" then\n      r[\"backup-status-activity\"]\n    else \"N/A\"\n    \n    }))\n"
    }
   ]
  },
  {
   "title": "Message Counter",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"global_stats\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"client-data-messages-received\" or r[\"_field\"] == \"client-data-messages-sent\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"client-data-messages-received\",\"client-data-messages-sent\"])\n"
    }
   ]
  },
  {
   "title": "Message Flow",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "global_stats",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"global_stats\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current-ingress-byte-rate-per-second\" or r[\"_field\"] == \"current-egress-byte-rate-per-second\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"current-ingress-byte-rate-per-second\",\"current-egress-byte-rate-per-second\"])\n",
     "select": [
      [
       {
        "params": [
         "current-ingress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "current-egress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Discards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "global_stats",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"global_stats\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-ingress-discards\" or r[\"_field\"] == \"total-egress-discards\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"total-ingress-discards\",\"total-egress-discards\"])\n",
     "select": [
      [
       {
        "params": [
         "current-ingress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "current-egress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "# Messages Spooled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"message_spool\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-messages-currently-spooled\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"total-messages-currently-spooled\"])"
    }
   ]
  },
  {
   "title": "Messages Spool Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"message_spool\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current-persist-usage\" or r[\"_field\"] == \"max-disk-usage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> map(fn: (r) => ({ r with spool_use_percent: r[\"current-persist-usage\"] / float(v: r[\"max-disk-usage\"])}))\n  |> keep(columns:[\"_time\",\"spool_use_percent\"])\n\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"physical-memory-usage-percent\" or r[\"_field\"] == \"subscription-memory-usage-percent\" or r[\"_field\"] == \"nab-buffer-load-factor\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"physical-memory-usage-percent\",\"subscription-memory-usage-percent\",\"nab-buffer-load-factor\"])"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_element\" and r[\"host\"] == \"${host}\" and r[\"name\"] == \"spool\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used-percentage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"used-percentage\"])"
    }
   ]
  },
  {
   "title": "Disk latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_health\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"disk-latency-current-value\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"disk-latency-current-value\"])"
    }
   ]
  },
  {
   "title": "Compute latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_health\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"compute-latency-current-value\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"compute-latency-current-value\"])"
    }
   ]
  },
  {
   "title": "Network Interface",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx-bytes\" or r[\"_field\"] == \"tx-bytes\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> derivative(columns:[\"rx-bytes\",\"tx-bytes\"])\n  |> keep(columns:[\"_time\",\"rx-bytes\",\"tx-bytes\"])\n"
    }
   ]
  },
  {
   "title": "Network & mate-link latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_health\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network-latency-current-value\" or r[\"_field\"] == \"mate-link-latency-current-value\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"network-latency-current-value\",\"mate-link-latency-current-value\"])"
    }
   ]
  },
  {
   "title": "VPN List",
   "type": "table",
   "description": " ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "repeat": "region",
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"local-status\" or r[\"_field\"] == \"connections\" or r[\"_field\"]==\"enabled\")\n  |> unique()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> filter(fn: (r) => r.enabled == true)\n  |> keep(columns:[\"message-vpn\",\"connections\",\"local-status\"])"
    }
   ]
  },
  {
   "title": "# Clients Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"global_stats\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-clients-connected\")\n"
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"redundancy\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"redundancy-status\" or r[\"_field\"] == \"config-status\" or r[\"_field\"] == \"adb-link-up\" or r[\"_field\"] == \"adb-hello-up\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"redundancy-status\",\"config-status\",\"adb-link-up\",\"adb-hello-up\"])"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"replication\" and r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bridge-admin-state\" or r[\"_field\"] == \"bridge-state\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> filter(fn: (r) => r[\"bridge-admin-state\"] == \"Enabled\")\n  |> keep(columns:[\"bridge-state\"])"
    }
   ]
  },
  {
   "title": "Config-sync Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"config_sync\" and r[\"host\"] == \"${host}\" and r[\"type\"]==\"Router\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sync-state\")\n  |> last()\n  |> group()"
    }
   ]
  }
 ]
}