{
 "title": "VPN",
 "description": "Message VPN Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"host\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "vpn",
    "label": "VPN",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"message-vpn\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"local-status\" or r[\"_field\"] == \"enabled\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\",\"message-vpn\"])\n  |> map(fn: (r) => ({ vpn_status: if r[\"enabled\"] then r[\"local-status\"] else \"Disabled\" }))"
    }
   ]
  },
  {
   "title": "# Clients Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn_stats\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"connections\")\n"
    }
   ]
  },
  {
   "title": "# Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-unique-subscriptions\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Client Types",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn_stats\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^connections-service/)\n  |> last()\n  |> group()\n  |> keep(columns: [\"_field\",\"_value\"])\n  |> rename(columns: {_field: \"Client Type\",_value: \"# connections\"})"
    }
   ]
  },
  {
   "title": "Slow Subscriber",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client_slow_subscriber\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num-subscriptions\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\",\"message-vpn\"])\n  |> keep(columns:[\"client-address\",\"num-subscriptions\"])\n  "
    }
   ]
  },
  {
   "title": "Config-sync Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"config_sync\" and r[\"host\"] == \"${host}\" and r[\"type\"]==\"Vpn\" and r[\"name\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sync-state\")\n  |> last()\n  |> group()"
    }
   ]
  },
  {
   "title": "# Messages Spooled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"message_spool_vpn\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current-messages-spooled\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"current-messages-spooled\"])"
    }
   ]
  },
  {
   "title": "Messages Spool Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"message_spool_vpn\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current-spool-usage-mb\" or r[\"_field\"] == \"maximum-spool-usage-mb\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> map(fn: (r) => ({ r with spool_use_percent: r[\"current-spool-usage-mb\"] / float(v: r[\"maximum-spool-usage-mb\"])}))\n  |> keep(columns:[\"_time\",\"spool_use_percent\"])\n\n"
    }
   ]
  },
  {
   "title": "Bridges",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bridge\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"admin-state\" or \n    r[\"_field\"] == \"inbound-operational-state\" or r[\"_field\"] == \"outbound-operational-state\" or r[\"_field\"] == \"queue-operational-state\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\",\"message-vpn\"])\n  |> keep(columns:[\"bridge-name\",\"admin-state\",\"inbound-operational-state\",\"outbound-operational-state\",\"queue-operational-state\"])\n  |> rename(columns: {\"admin-state\": \"State\", \"inbound-operational-state\":\"Inbound State\", \"outbound-operational-state\":\"Outbound State\", \"queue-operational-state\":\"Queue State\"})\n"
    }
   ]
  },
  {
   "title": "Message Counter",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn_stats\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"client-data-messages-received\" or r[\"_field\"] == \"client-data-messages-sent\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"client-data-messages-received\",\"client-data-messages-sent\"])"
    }
   ]
  },
  {
   "title": "Message Flow",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "global_stats",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn_stats\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current-ingress-byte-rate-per-second\" or r[\"_field\"] == \"current-egress-byte-rate-per-second\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"current-ingress-byte-rate-per-second\",\"current-egress-byte-rate-per-second\"])\n",
     "select": [
      [
       {
        "params": [
         "current-ingress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "current-egress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Discards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "global_stats",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vpn_stats\" and r[\"host\"] == \"${host}\" and r[\"message-vpn\"] == \"${vpn}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-ingress-discards\" or r[\"_field\"] == \"total-egress-discards\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns:[\"host\"])\n  |> keep(columns:[\"_time\",\"total-ingress-discards\",\"total-egress-discards\"])\n",
     "select": [
      [
       {
        "params": [
         "current-ingress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "current-egress-byte-rate-per-second"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}